.TH "Atom" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Atom
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAtom\fP (glm::vec3 position, float radius)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
