.TH "FrustumPlane" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrustumPlane
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrustumPlane\fP (const glm::vec3 &v1, const glm::vec3 &v2, const glm::vec3 &v3)"
.br
.ti -1c
.RI "void \fBset3Points\fP (const glm::vec3 &v1, const glm::vec3 &v2, const glm::vec3 &v3)"
.br
.ti -1c
.RI "float \fBdistance\fP (const glm::vec3 &p) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBnormal\fP"
.br
.ti -1c
.RI "glm::vec3 \fBpoint\fP"
.br
.ti -1c
.RI "float \fBd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
