.TH "GeometryData" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeometryData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< glm::vec3 > \fBpositions\fP"
.br
.ti -1c
.RI "std::vector< glm::vec3 > \fBnormals\fP"
.br
.ti -1c
.RI "std::vector< glm::vec2 > \fBuv\fP"
.br
.ti -1c
.RI "std::vector< unsigned int > \fBindices\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
