.TH "LambertMaterial" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LambertMaterial
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaterial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLambertMaterial\fP (std::shared_ptr< \fBShader\fP > shader, glm::vec3 ambient, glm::vec3 diffuse, glm::vec3 specular, float specularCoefficient)"
.br
.ti -1c
.RI "\fBLambertMaterial\fP (std::shared_ptr< \fBShader\fP > shader)"
.br
.ti -1c
.RI "virtual void \fBsetColor\fP (glm::vec3 color)"
.br
.ti -1c
.RI "virtual void \fBsetUniforms\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
