.TH "Light" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDirectionalLight\fP, \fBPointLight\fP, and \fBSpotLight\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetUniforms\fP (const std::vector< std::shared_ptr< \fBShader\fP >> &shaders, int index) final"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetUniform\fP (std::shared_ptr< \fBShader\fP > &shader, int index)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
