.TH "Molecule" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Molecule
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBAtom\fP > \fBatoms\fP"
.br
.ti -1c
.RI "glm::vec3 \fBmax_pos\fP"
.br
.ti -1c
.RI "glm::vec3 \fBmin_pos\fP"
.br
.ti -1c
.RI "float \fBmax_radius\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
