.TH "PDBLoader" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PDBLoader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPDBLoader\fP (const std::string &dir)"
.br
.ti -1c
.RI "\fBMolecule\fP \fBgetMolecule\fP ()"
.br
.ti -1c
.RI "void \fBbuildAtomTable\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
