.TH "SpotLight" 3 "Mon Jun 3 2019" "Molecular Vis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpotLight
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLight\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpotLight\fP (glm::vec3 color, glm::vec3 position, glm::vec3 direction, float innerOpeningAngle, float outerOpeningAngle, glm::vec3 attenuation)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetUniform\fP (std::shared_ptr< \fBShader\fP > &shader, int index)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Molecular Vis from the source code\&.
